# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=256)),
                ('associated_name_type', models.CharField(max_length=256)),
                ('entity_type', models.CharField(max_length=256)),
                ('nonprofit_type', models.CharField(max_length=256)),
                ('zip_code', models.IntegerField()),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=128)),
                ('registry_number', models.IntegerField()),
                ('registry_date', models.DateTimeField()),
                ('state', models.CharField(max_length=256)),
            ],
        ),
    ]
