# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='organization',
            name='associated_name_type',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='organization',
            name='business_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='organization',
            name='entity_type',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='organization',
            name='nonprofit_type',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registry_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='organization',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
